timeZone: America/Los_Angeles
weather:
  userAgent: snow.kye.dev
  baseUrl: "https://api.weather.gov"
timberline:
  timeZone: America/Los_Angeles
  parkUrl: "https://www.timberlinelodge.com/conditions"
  noaaUrl: "https://forecast.weather.gov/MapClick.php?lat=45.33284041773058&lon=-121.70877456665039&site=all"
  weather:
    # point: "45.3328,-121.7088"
    office: PQR
    grid:
      id: PQR
      x: 141
      "y": 88
skiBowl:
  timeZone: America/Los_Angeles
  parkUrl: "https://skibowl.com/winter-condition-and-lift-status/"
  noaaUrl: "https://forecast.weather.gov/MapClick.php?lat=45.302189&lon=-121.750504&site=all"
  weather:
    # point: "45.31,-121.77"
    station: ODT75
    office: PQR
    grid:
      id: PQR
      x: 139
      "y": 87
meadows:
  timeZone: America/Los_Angeles
  parkUrl: "https://www.skihood.com/mountain-report"
  noaaUrl: "https://forecast.weather.gov/MapClick.php?lat=45.3282&lon=-121.6623"
  weather:
    # point: "45.34357,-121.67227"
    office: PQR
    station: KRTX
    grid:
      id: PQR
      x: 143
      "y": 88
