services:
  snow-tracker:
    image: docker.local.kye.ev/snow-tracker:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - snow-data:/data
    labels:
      stook.image: "snow-tracker"

volumes:
  snow-data:
